version: '3.8'

services:
  # The PostgreSQL Database Service
  db:
    image: postgres:16 # Using the official PostgreSQL image
    container_name: quiz-postgres-db
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432" # Map the PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # The Spring Boot Application Service
  app:
    build: .
    container_name: quiz-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Update the database URL and credentials for PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quiz_db
      SPRING_DATASOURCE_USERNAME: your_postgres_user
      SPRING_DATASOURCE_PASSWORD: your_strong_password
      # Mail credentials remain the same
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: your_email@gmail.com
      SPRING_MAIL_PASSWORD: your_gmail_app_password

volumes:
  postgres-data: